spring:
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  application:
    name: order-management-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

# Custom Feature Switches
api:
  docs:
    enabled: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: io.github.liuliu.ordermanagement.domain.entity,io.github.liuliu.ordermanagement.domain.dto,io.github.liuliu.ordermanagement.domain.enumtype
  type-handlers-package: io.github.liuliu.ordermanagement.domain.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    url: /openapi.yaml
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  override-with-generic-response: false

server:
  jetty:
    accesslog:
      enabled: true

logging:
#  pattern:
#    correlation: "[req=%X{requestId:-},trace=%X{traceId:-},span=%X{spanId:-}] "
  include-application-name: false
  structured:
    format:
      console: ecs
  level:
    root: INFO
    io.github.liuliu.ordermanagement: DEBUG
    org.springdoc: INFO

observability:
  otlp:
    base-url: ${OBSERVABILITY_OTLP_BASE_URL:http://localhost:4318}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  tracing:
    sampling:
      probability: 0.1   # prod 只追蹤少量
    propagation:
      type: W3C
  otlp:
    metrics:
      export:
        url: ${observability.otlp.base-url}/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${observability.otlp.base-url}/v1/traces
